version: 2.1
orbs:
  node: circleci/node@5.1.0
executors:
  sdf:
    docker:
      - image: cimg/openjdk:19.0-node
        environment:
          TZ: America/New_York
commands:
  test:
    description: Runs unit test suite without code coverage
    steps:
      - node/test:
          run-command: test-ci
          override-ci-command: npm ci --acceptsuitecloudsdklicense
          test-results-for: jest
          test-results-path: reports
  test-coverage:
    description: Runs unit test suite with code coverage
    steps:
      - node/test:
          run-command: test-ci-coverage
          override-ci-command: npm ci --acceptsuitecloudsdklicense
          test-results-for: jest
          test-results-path: reports
      - store_artifacts:
          path: reports/lcov
jobs:
  test:
    executor: sdf
    steps:
      - test
  test-coverage:
    executor: sdf
    steps:
      - test-coverage
workflows:
  main:
    jobs:
      - test-coverage
