version: 2.1
orbs:
  node: circleci/node@5.1.0
workflows:
  main:
    jobs:
      - node/test:
          resource_class: small
          run-command: test-ci-coverage
          override-ci-command: npm ci --acceptsuitecloudsdklicense
          test-results-for: jest
          post-steps:
            - store_artifacts:
                path: reports/coverage
            - lint
            - validate
      - hold:
          type: approval
          requires:
            - node/test
      - deploy:
          requires:
            - hold
parameters:
  netsuite_account:
    type: enum
    enum: [ "3751499", "3751499_SB1", "3751499_SB2" ]
    default: "3751499_SB1"
jobs:
  deploy:
    executor: sdf
    steps:
      - install
      - run: npm run sdf-deploy
commands:
  install:
    description: Checks out code and installs npm package
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm ci --acceptsuitecloudsdklicense
  lint:
    description: Lint all code and save results
    steps:
      - run: npm run lint-ci
      - store_artifacts:
          path: reports/eslint.html
  save-token:
    description: |
      Create an SDF Token for the specified environment. Assumes 'suitecloud' is on the PATH
    parameters:
      account:
        description: The NetSuite Account ID
        type: enum
        enum: [ "3751499", "3751499_SB1", "3751499_SB2" ]
        default: "3751499_SB1"
      tokenid:
        description: The NetSuite Token ID
        type: string
      tokensecret:
        description: The NetSuite Token Secret
        type: string
    steps:
      - run: |
          suitecloud account:savetoken --account << parameters.account >> --authid << parameters.account >> --tokenid << parameters.tokenid >> --tokensecret << parameters.tokensecret >>
  validate:
    description: Validate the SDF Project
    steps:
      - run: npm run sdf-validate
executors:
  sdf:
    resource_class: small
    docker:
      - image: cimg/openjdk:19.0-node
        environment:
          TZ: America/New_York
