version: 2.1
orbs:
  node: circleci/node@5.1.0
executors:
  sdf:
    docker:
      - image: cimg/openjdk:19.0-node
        environment:
          TZ: America/New_York
workflows:
  test:
    jobs:
      - node/test:
          run-command: test-ci
          override-ci-command: npm ci --acceptsuitecloudsdklicense
          test-results-for: jest
          test-results-path: reports
  test-coverage:
    jobs:
      - node/test:
          run-command: test-ci-coverage
          override-ci-command: npm ci --acceptsuitecloudsdklicense
          test-results-for: jest
          test-results-path: reports
