version: 2.1
orbs:
  node: circleci/node@5.1.0
workflows:
  main:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
parameters:
  netsuite_account:
    description: The Account ID for the target NetSuite environment
    type: enum
    enum: [ "3751499", "3751499_SB1", "3751499_SB2" ]
    default: "3751499_SB1"
  commit_reference:
    description: The git commit reference (commit hash, branch name, tag name, etc) to operate on
    type: string
    default: ''
jobs:
  build:
    executor: sdf
    steps:
      - install:
          project: compass
      - test:
          project: compass
          with-coverage: true
      - lint:
          project: compass
      - validate:
          account: << pipeline.parameters.netsuite_account >>
          project: compass
          token_id: $SB1_TOKEN_ID
          token_secret: $SB1_TOKEN_SECRET
  deploy:
    executor: sdf
    steps:
      - install
      - deploy:
          account: << pipeline.parameters.netsuite_account >>
          project: compass
          token_id: $SB1_TOKEN_ID
          token_secret: $SB1_TOKEN_SECRET
commands:
  deploy:
    description: Deploys the SDF Project
    parameters:
      account:
        description: The NetSuite Account ID
        type: enum
        enum: [ "3751499", "3751499_SB1", "3751499_SB2" ]
        default: "3751499_SB1"
      project:
        description: The SDF Project to deploy
        type: enum
        enum: [ "compass", "compass-workflows", "compass-objects" ]
        default: compass
      token_id:
        description: The NetSuite Token ID
        type: string
      token_secret:
        description: The NetSuite Token Secret
        type: string
    steps:
      - run:
          name: Deploying << parameters.project >>
          command: |
            export PATH=$PATH:~/project/<< parameters.project >>/node_modules/.bin
            cd << parameters.project >>
            suitecloud account:savetoken --account << parameters.account >> --authid << parameters.account >> --tokenid << parameters.token_id >> --tokensecret << parameters.token_secret >>
            npm run sdf-deploy
      - store_artifacts:
          path: << parameters.project >>/build
  install:
    description: Checks out code and installs npm package
    parameters:
      project:
        description: The SDF Project to install
        type: enum
        enum: [ "compass", "compass-workflows", "compass-objects" ]
        default: compass
    steps:
      - checkout
      - npm-config
      - node/install-packages:
          app-dir: ./<< parameters.project >>
          override-ci-command: npm ci --acceptsuitecloudsdklicense
  lint:
    description: Lint all code and save results
    parameters:
      project:
        description: The SDF Project to lint
        type: enum
        enum: [ "compass", "compass-workflows", "compass-objects" ]
        default: compass
    steps:
      - run:
          name: Linting << parameters.project >>
          command: |
            npm run lint-ci --prefix ./<< parameters.project >>
      - store_artifacts:
          path: << parameters.project >>/reports/eslint.html
  npm-config:
    description: Configure npm to use Nexus
    steps:
      - run:
          name: Configuring npm
          command: |
            printf "email=$ARTIFACT_STORE_EMAIL
            always-auth=true
            registry=https://artifacts.compass-tech.net/repository/npm
            //artifacts.compass-tech.net/repository/:_auth=$ARTIFACT_STORE_NPM_AUTH
            //artifacts.compass-tech.net/repository/:_password=$ARTIFACT_STORE_NPM_PASS
            //artifacts.compass-tech.net/repository/:username=$ARTIFACT_STORE_NPM_USER
            //artifacts.compass-tech.net/repository/:email=$ARTIFACT_STORE_EMAIL
            //artifacts.compass-tech.net/repository/:always-auth=true" > ~/.npmrc
  test:
    description: Test the SDF Project, optionally producing a code coverage report as well
    parameters:
      with-coverage:
        description: |
          Determines whether the test suite will generate a code coverage report.
          true to generate code coverage report; false otherwise.
        type: boolean
        default: true
      project:
        description: The SDF Project to test
        type: enum
        enum: [ "compass", "compass-workflows", "compass-objects" ]
        default: compass
    steps:
      - when:
          condition: << parameters.with-coverage >>
          steps:
            - run:
                name: Unit testing << parameters.project >>
                command: |
                  npm run test-ci-coverage --prefix ./<< parameters.project >>
            - store_artifacts:
                path: << parameters.project >>/reports/coverage
      - unless:
          condition: << parameters.with-coverage >>
          steps:
            - run:
                name: Unit Test << parameters.project >>
                command: |
                  npm run test-ci --prefix ./<< parameters.project >>
      - store_test_results:
          path: << parameters.project >>/reports/jest.xml
  validate:
    description: Validate the SDF Project
    parameters:
      account:
        description: The NetSuite Account ID
        type: enum
        enum: [ "3751499", "3751499_SB1", "3751499_SB2" ]
        default: "3751499_SB1"
      project:
        description: The SDF Project to test
        type: enum
        enum: [ "compass", "compass-workflows", "compass-objects" ]
        default: compass
      token_id:
        description: The NetSuite Token ID
        type: string
      token_secret:
        description: The NetSuite Token Secret
        type: string
    steps:
      - run:
          name: Validating << parameters.project >>
          command: |
            export PATH=$PATH:~/project/<< parameters.project >>/node_modules/.bin
            cd << parameters.project >>
            suitecloud account:savetoken --account << parameters.account >> --authid << parameters.account >> --tokenid << parameters.token_id >> --tokensecret << parameters.token_secret >>
            npm run sdf-validate
executors:
  sdf:
    resource_class: small
    docker:
      - image: cimg/openjdk:17.0-node
        environment:
          TZ: America/New_York
