version: 2.1
orbs:
  node: circleci/node@5.1.0
executors:
  sdf:
    docker:
      - image: cimg/openjdk:19.0-node
        environment:
          TZ: America/New_York
    working_directory: /home/circleci/project/
workflows:
  test:
    jobs:
      - node/test:
          test-results-for: jest
