version: 2.1
orbs:
  node: circleci/node@5.1.0
workflows:
  main:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
parameters:
  netsuite_account:
    description: The Account ID for the target NetSuite environment
    type: enum
    enum: [ "3751499", "3751499_SB1", "3751499_SB2" ]
    default: "3751499_SB1"
  commit_reference:
    description: The git commit reference (commit hash, branch name, tag name, etc) to operate on
    type: string
    default: ''
jobs:
  build:
    executor: sdf
    steps:
      - install
      - test:
          with-coverage: true
      - lint
      - validate:
          account: << pipeline.parameters.netsuite_account >>
          token_id: $SB1_TOKEN_ID
          token_secret: $SB1_TOKEN_SECRET
  deploy:
    executor: sdf
    steps:
      - install
      - deploy:
          account: << pipeline.parameters.netsuite_account >>
          token_id: $SB1_TOKEN_ID
          token_secret: $SB1_TOKEN_SECRET
commands:
  deploy:
    description: Deploys the SDF Project
    parameters:
      account:
        description: The NetSuite Account ID
        type: enum
        enum: [ "3751499", "3751499_SB1", "3751499_SB2" ]
        default: "3751499_SB1"
      token_id:
        description: The NetSuite Token ID
        type: string
      token_secret:
        description: The NetSuite Token Secret
        type: string
    steps:
      - run: |
          export PATH=$PATH:/home/circleci/project/node_modules/.bin
          suitecloud account:savetoken --account << parameters.account >> --authid << parameters.account >> --tokenid << parameters.token_id >> --tokensecret << parameters.token_secret >>
          npm run sdf-deploy
  install:
    description: Checks out code and installs npm package
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm ci --acceptsuitecloudsdklicense
  lint:
    description: Lint all code and save results
    steps:
      - run: npm run lint-ci
      - store_artifacts:
          path: reports/eslint.html
  test:
    description: Test the SDF Project, optionally producing a code coverage report as well
    parameters:
      with-coverage:
        description: |
          Determines whether the test suite will generate a code coverage report.
          true to generate code coverage report; false otherwise.
        type: boolean
        default: true
    steps:
      - when:
          condition: << parameters.with-coverage >>
          steps:
            - run: npm run test-ci-coverage
            - store_artifacts:
                path: reports/coverage
      - unless:
          condition: << parameters.with-coverage >>
          steps:
            - run: npm run test-ci
      - store_test_results:
          path: reports/jest.xml
  validate:
    description: Validate the SDF Project
    parameters:
      account:
        description: The NetSuite Account ID
        type: enum
        enum: [ "3751499", "3751499_SB1", "3751499_SB2" ]
        default: "3751499_SB1"
      token_id:
        description: The NetSuite Token ID
        type: string
      token_secret:
        description: The NetSuite Token Secret
        type: string
    steps:
      - run: |
          export PATH=$PATH:/home/circleci/project/node_modules/.bin
          suitecloud account:savetoken --account << parameters.account >> --authid << parameters.account >> --tokenid << parameters.token_id >> --tokensecret << parameters.token_secret >>
          npm run sdf-validate
executors:
  sdf:
    resource_class: small
    docker:
      - image: cimg/openjdk:19.0-node
        environment:
          TZ: America/New_York
