version: 2.1
executors:
  sdf:
    docker:
      - image: cimg/openjdk:19.0-node
        environment:
          TZ: America/New_York
    working_directory: /home/circleci/project/
commands:
  setup-env:
    description: Fully configures the environment for use with SDF
    steps:
      - setup-npm
      - setup-sdf
  setup-npm:
    description: Configures npm
    steps:
      - run:
          name: Configure npm
          command: |
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            sudo chown -R `whoami` /usr/local/lib/node_modules
            sudo chown -R `whoami` ~/.npm-global
            echo "export PATH=~/.npm-global/bin:$PATH" >> $BASH_ENV
            source ~/.profile
  setup-sdf:
    description: Installs SDF
    steps:
      - run:
          name: Install SDF
          command: |
            npm install -g @oracle/suitecloud-unit-testing jest @oracle/suitecloud-cli --acceptsuitecloudsdklicense 
            echo "suitecloud version: $(suitecloud --version)"

jobs:
  say-hello:
    executor: sdf
    steps:
      - checkout
      - setup-env
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
