version: 2.1
orbs:
  node: circleci/node@5.1.0
executors:
  sdf:
    resource_class: small
    docker:
      - image: cimg/openjdk:19.0-node
        environment:
          TZ: America/New_York
commands:
  install:
    description: Checks out code and installs npm package
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm ci --acceptsuitecloudsdklicense
  lint:
    description: Run linter and store results as an artifact
    steps:
      - run: npm run lint-ci
      - store_artifacts:
          path: reports/eslint.html
jobs:
  deploy:
    executor: sdf
    steps:
      - install
      - run: npm run deploy
workflows:
  main:
    jobs:
      - node/test:
          resource_class: small
          run-command: test-ci-coverage
          override-ci-command: npm ci --acceptsuitecloudsdklicense
          test-results-for: jest
          post-steps:
            - store_artifacts:
                path: reports/coverage
            - lint
      - hold:
          type: approval
          requires:
            - node/test
      - deploy:
          requires:
            - hold
