version: 2.1
orbs:
  node: circleci/node@5.1.0
executors:
  sdf:
    docker:
      - image: cimg/openjdk:19.0-node
        environment:
          TZ: America/New_York
    working_directory: /home/circleci/project/
commands:
jobs:
  build_and_test:
    executor: sdf
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Unit Tests
